# Generated by Django 3.1.3 on 2020-11-20 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LaBontaApp', '0002_auto_20201115_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='takeorder',
            name='price',
        ),
    ]
