# Generated by Django 2.2.3 on 2020-11-28 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LaBontaApp', '0003_remove_takeorder_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='provClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('Pizza', 'Pizza'), ('Pasta', 'Pasta')], max_length=20, null=True)),
            ],
        ),
    ]
