# Generated by Django 3.0 on 2020-11-28 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LaBontaApp', '0004_provclass'),
    ]

    operations = [
        migrations.DeleteModel(
            name='provClass',
        ),
    ]
