# Generated by Django 2.2.3 on 2020-12-01 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LaBontaApp', '0005_delete_provclass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='section_type',
        ),
    ]
