# Generated by Django 2.2.3 on 2020-12-01 11:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('LaBontaApp', '0006_remove_delivery_section_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='section_type',
            field=models.CharField(choices=[('Pizza', 'Pizza'), ('Pasta', 'Pasta'), ('Salad', 'Salad'), ('Drinks', 'Drinks'), ('Breakfast', 'Breakfast'), ('Appetizer', 'Appetizer'), ('Wine List', 'Wine List'), ('Meat', 'Meat')], default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
