# Generated by Django 2.2.3 on 2020-12-01 12:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('LaBontaApp', '0007_delivery_section_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Pizza', 'Pizza'), ('Pasta', 'Pasta'), ('Salad', 'Salad'), ('Drinks', 'Drinks'), ('Breakfast', 'Breakfast'), ('Appetizer', 'Appetizer'), ('Wine List', 'Wine List'), ('Meat', 'Meat')], max_length=15)),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='takeorder',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='takeorder',
            name='status',
            field=models.CharField(choices=[('U Pranua', 'U Pranua'), ('U Dergua', 'U Dergua'), ('U Refuzua', 'U Refuzua')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='delivery',
            name='section_type',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='takeorder',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='LaBontaApp.Product'),
        ),
    ]
