# Generated by Django 2.2.3 on 2020-12-01 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LaBontaApp', '0012_product_food_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='food_category',
        ),
    ]
