# Generated by Django 2.2.3 on 2020-12-08 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LaBontaApp', '0017_auto_20201201_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downlodableitems',
            name='item_header',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='LaBontaApp.Order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='LaBontaApp.Product'),
        ),
    ]
