# Generated by Django 2.2.3 on 2020-12-08 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LaBontaApp', '0018_auto_20201208_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='downloadMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_to_download', models.FileField(blank=True, upload_to='media/DownlodableItems')),
                ('to_download_file_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MenuList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_header', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='DownlodableItems',
        ),
        migrations.AddField(
            model_name='downloadmenu',
            name='item_header',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='LaBontaApp.MenuList'),
        ),
    ]
