# Generated by Django 2.2.3 on 2020-12-08 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LaBontaApp', '0019_auto_20201208_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownlodableItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_header', models.CharField(max_length=35)),
                ('item_to_download', models.FileField(blank=True, upload_to='media/DownlodableItems')),
                ('to_download_file_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='downloadMenu',
        ),
        migrations.DeleteModel(
            name='MenuList',
        ),
    ]
